spring:
  application:
    name: attendance-service
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER}

supabase:
  url: ${SUPABASE_URL}

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: framework

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,
     http://localhost:3000,tauri://localhost}

